// Teksty strony. Kolejność języków (Daniel 02.10.2026): FR, EN, ES, PL, RU, DE.
// Od 03.10.2026 (Daniel: „lecimy z językami”) komplet 6 języków. Brakujący klucz = tekst francuski + pasek
// „traduction en préparation”. Wiadomość z prośbą o wizytę (rdv_msg_*, rdv_mail_sujet) idzie do Moniki, więc w EN, ES,
// RU i DE zostaje po francusku; w PL po polsku (Monika czyta francuski i polski).
window.JEZYKI = ['fr', 'en', 'es', 'pl', 'ru', 'de'];
window.NAZWY_JEZYKOW = { fr: 'FR', en: 'EN', es: 'ES', pl: 'PL', ru: 'RU', de: 'DE' };

window.T = {
  fr: {
    meta_title: 'Evolution Body Lab · Remodelage de la silhouette à Nice',
    meta_desc: 'EMS et cryolipolyse à Nice. Tarifs affichés, première visite sur rendez-vous, du lundi au vendredi.',
    nav_accueil: 'Accueil', nav_soins: 'Soins', nav_tarifs: 'Tarifs', nav_visite: 'Première visite', nav_monika: 'Monika', nav_faq: 'Questions', nav_contact: 'Contact',
    cta_rdv: 'Prendre rendez-vous', cta_rdv_court: 'Rendez-vous', cta_soins: 'Voir les soins', cta_appeler: 'Appeler', cta_whatsapp: 'WhatsApp',
    demo: 'Version de démonstration : coordonnées, tarifs et images sont provisoires.',
    traduction: 'Traduction en préparation : le texte s’affiche en français.',
    image_synthese: 'Image de synthèse',
    ilustracja_alt: 'Illustration Evolution Body Lab',
    h_sur: 'Nice · Côte d’Azur',
    h_titre: 'Remodelage de la silhouette à Nice',
    h_lead: 'Deux soins, un protocole clair dès la première séance et des tarifs affichés. Sur rendez-vous, du lundi au vendredi.',
    h_info: 'Monika vous reçoit en français et en polonais.',
    h_wielki: 'Evolution',   // gigantyczny napis za Moniką w pierwszym ekranie (jak u Lando)
    h_pas_1: 'EMS · Cryolipolyse · Nice · ',
    h_pas_2: 'Silhouette · Fermeté · Côte d’Azur · ',
    st_1: 'Rendez-vous', st_2: 'Bilan', st_3: 'Protocole', st_4: 'Séance', st_5: 'Suivi', st_6: 'Évolution',
    man_label: 'Notre approche',
    manifeste: 'Un protocole *clair*. Des tarifs *affichés*. Des soins *précis*, à Nice.',
    // Teleport (#approche, js/petardy.js): wskazówka nad medalionem
    portal_entrer: 'Faites défiler pour entrer',
    obj_label: 'Vos objectifs',
    obj_titre: 'Par où commencer ?',
    obj_1_t: 'Tonicité', obj_1_d: 'Travailler les muscles en séances courtes et régulières.',
    obj_2_t: 'Fermeté', obj_2_d: 'Un rythme de séances pour travailler la tonicité du corps.',
    obj_3_t: 'Silhouette', obj_3_d: 'Ventre, hanches, cuisses : un travail ciblé, zone par zone.',
    obj_4_t: 'Régularité', obj_4_d: 'Un rythme de séances planifié, suivi par des mesures.',
    soins_label: 'Les soins',
    soins_titre: 'Chaque soin et son prix',
    soins_fond: 'Soins',
    soins_defiler: 'Faites défiler',
    soins_fin: 'Le soin adapté, le nombre de séances et le prix total sont fixés lors de la première visite.',
    soins_test: 'Deux soins seulement : l’EMS et la cryolipolyse.',
    // Tor 3 paneli (#soins, js/petardy.js): wielki napis w tle i link trzeciego panelu
    tor_fond: 'Evolution Body Lab',
    tor_3_lien: 'Le déroulé de la visite',
    tor_3_nad: 'Avant tout soin · consultation',   // podpis nad „Première visite” w torze: zamknięcie toru, nie trzeci zabieg
    s_ems_t: 'EMS', s_ems_d: 'Électrostimulation musculaire en séance encadrée : un entraînement régulier, planifié avec vous.',
    s_cryo_t: 'Cryolipolyse', s_cryo_d: 'Un froid contrôlé, appliqué sur une zone précise. 180 € une zone, 350 € deux zones, 500 € trois zones.',
    duree: 'min', prix_tbc: 'Tarif à confirmer (TEST)', par_seance: 'la séance', a_partir: 'à partir de', reserver_soin: 'Réserver ce soin',
    visite_label: 'Première visite',
    visite_mot_1: 'Première',
    visite_mot_2: 'visite',
    visite_titre: 'Comment se passe la première visite',
    v1_t: 'Échange', v1_d: 'Vos objectifs, vos antécédents, un questionnaire rempli sur place.',
    v2_t: 'Mesures', v2_d: 'Prise de mesures pour suivre vos résultats séance après séance.',
    v3_t: 'Protocole', v3_d: 'Le soin adapté, le nombre de séances et leur rythme, le prix total.',
    v4_t: 'Premier soin', v4_d: 'Si vous le souhaitez, le premier soin a lieu le jour même.',
    visite_pratique: 'Prévoir environ 1 h. Tenue confortable, aucune préparation particulière.',
    monika_label: 'Votre praticienne',
    monika_titre: 'Monika',
    monika_alt: "Monika, Evolution Body Lab",
    monika_fond: 'Monika',
    monika_citation: 'Citation de Monika à venir (TEST)',
    monika_txt: 'Présentation, parcours et certifications à venir (TEST).',
    monika_langues: 'Langues : français, polonais.',
    faq_label: 'Questions fréquentes',
    faq_titre: 'Avant de réserver',
    q1: 'Est-ce douloureux ?', a1: 'La plupart des soins sont confortables. Une sensation de chaleur, de froid ou de pression est possible selon la technique ; on en parle avant de commencer.',
    q2: 'Combien de séances faut-il ?', a2: 'Cela dépend du soin et de votre objectif. Le nombre de séances et le prix total sont fixés lors de la première visite, avant tout engagement.',
    q3: 'Y a-t-il des contre-indications ?', a3: 'Oui, selon les soins : grossesse, certains traitements ou problèmes de santé. Le questionnaire de la première visite sert à les vérifier.',
    q4: 'Puis-je annuler mon rendez-vous ?', a4: 'Oui. Conditions d’annulation à confirmer (TEST).',
    q5: 'Les résultats sont-ils garantis ?', a5: 'Non, et personne ne peut honnêtement les garantir. Les résultats varient selon chaque personne ; nous les suivons avec des mesures régulières.',
    contact_label: 'Contact',
    contact_titre: 'Réserver votre visite',
    horaires: 'Horaires', horaires_val: 'Du lundi au vendredi, 9 h à 19 h · dernier rendez-vous à 18 h',
    weekend: 'Fermé le samedi et le dimanche',
    adresse: 'Adresse', telephone: 'Téléphone', langues: 'Langues', langues_val: 'Monika parle français et polonais',
    rdv_off: 'La réservation en ligne ouvrira avec l’institut. En attendant, appelez ou écrivez sur WhatsApp.',
    // Cennik (#tarifs): ceny z js/dane.js (biznesplan Moniki), tu tylko słowa wokół liczb
    tarifs_label: 'Tarifs',
    tarifs_titre: 'La carte des soins',
    tarifs_ems_sous: 'Électrostimulation musculaire',
    tarifs_cryo_sous: 'Froid contrôlé, zone par zone',
    tarif_seance: 'La séance', tarif_zone: 'zone', tarif_zones: 'zones',
    tarif_test: 'À valider (TEST)',
    tarifs_note: 'Prix TTC. Le protocole et le nombre de séances sont fixés ensemble lors de la première visite.',
    // Demande de rendez-vous (#contact, js/rezerwacja.js). Jamais de réservation présentée comme acquise.
    rdv_lead: 'Choisissez un soin, un jour et une heure. Votre demande part sur WhatsApp ou par e-mail, puis l’institut vous répond pour fixer le rendez-vous.',
    rdv_etapes: 'Étapes de la demande',
    rdv_e1: 'Soin', rdv_e2: 'Date et heure', rdv_e3: 'Coordon\u00adnées',
    rdv_etape_sur: 'Étape {n} sur 3',
    rdv_k1_t: 'Quel soin vous intéresse ?',
    rdv_conseil_t: 'Première visite – conseil', rdv_conseil_d: 'Échange, mesures et protocole adapté',
    rdv_k2_t: 'Quel jour vous conviendrait ?',
    rdv_mois_prec: 'Mois précédent', rdv_mois_suiv: 'Mois suivant',
    rdv_aujourdhui: 'aujourd’hui', rdv_ferme: 'fermé', rdv_indispo: 'indisponible', rdv_choisi: 'sélectionné',
    rdv_heure: 'Heure souhaitée', rdv_heure_vide: 'Choisissez d’abord un jour dans le calendrier.',
    rdv_k3_t: 'Vos coordonnées',
    rdv_nom: 'Prénom et nom', rdv_tel: 'Téléphone', rdv_mail: 'E-mail', rdv_facultatif: '(facultatif)', rdv_message: 'Message',
    rdv_tel_aide: 'Exemple : 06 12 34 56 78 ou +33 6 12 34 56 78',
    rdv_message_aide: 'Une question, une préférence d’horaire… Merci de ne pas indiquer d’informations de santé : on en parle sur place, lors de la première visite.',
    rdv_accord: 'J’accepte qu’Evolution Body Lab me recontacte au sujet de cette demande.',
    rdv_vie_privee: 'Rien n’est enregistré sur ce site : la demande part depuis votre WhatsApp ou votre messagerie.',
    rdv_continuer: 'Continuer', rdv_retour: 'Retour', rdv_preparer: 'Préparer ma demande',
    rdv_err_soin: 'Choisissez un soin pour continuer.',
    rdv_err_date: 'Choisissez un jour, puis une heure.',
    rdv_err_nom: 'Indiquez votre prénom et votre nom.',
    rdv_err_tel: 'Numéro non reconnu. Exemple : 06 12 34 56 78 ou +33 6 12 34 56 78.',
    rdv_err_mail: 'Adresse e-mail non valide.',
    rdv_err_accord: 'Cochez la case pour que l’institut puisse vous recontacter.',
    rdv_recap_soin: 'Soin', rdv_recap_date: 'Date', rdv_recap_heure: 'Heure', rdv_vide: '—',
    rdv_pret_t: 'Demande prête à envoyer',
    rdv_pret_d: 'Ce n’est pas encore un rendez-vous : l’institut vous répond pour fixer le créneau.',
    rdv_envoyer_wa: 'Envoyer sur WhatsApp', rdv_envoyer_mail: 'Envoyer par e-mail', rdv_modifier: 'Modifier ma demande',
    rdv_appel_t: 'Vous préférez en parler ?',
    rdv_msg_bonjour: 'Bonjour, je souhaite demander un rendez-vous chez Evolution Body Lab.',
    rdv_msg_soin: 'Soin', rdv_msg_date: 'Date souhaitée', rdv_msg_heure: 'Heure souhaitée',
    rdv_msg_nom: 'Nom', rdv_msg_tel: 'Téléphone', rdv_msg_mail: 'E-mail', rdv_msg_message: 'Message',
    rdv_msg_fin: 'Merci de me recontacter pour fixer le rendez-vous.',
    rdv_mail_sujet: 'Demande de rendez-vous',
    footer_legal: 'Mentions légales', footer_siret: 'SIRET',
    footer_slogan: 'Chaque soin a sa *méthode*.',
    footer_pages: 'Pages', footer_contact: 'Contact',
    // Kursor-soczewka (js/efekty.js, tylko komputer z myszą): słowo w złotym kółku nad kartami, torem i zdjęciami
    kursor_voir: 'Voir', kursor_reserver: 'Réserver', kursor_glisser: 'Glisser',
    // Menu plein écran (js/silnik2.js, ordinateur) : bouton du bandeau, fermeture, nom de la navigation, langues
    menu_ouvrir: 'Ouvrir le menu', menu_fermer: 'Fermer le menu', menu_nav: 'Navigation', menu_langues: 'Langues'
  },
  en: {
    meta_title: "Evolution Body Lab · Body contouring in Nice",
    meta_desc: "EMS and cryolipolysis in Nice. Prices shown upfront, first visit by appointment, Monday to Friday.",
    nav_accueil: "Home",
    nav_soins: "Treatments",
    nav_tarifs: "Prices",
    nav_visite: "First visit",
    nav_monika: "Monika",
    nav_faq: "Questions",
    nav_contact: "Contact",
    cta_rdv: "Book a visit",
    cta_rdv_court: "Book",
    cta_soins: "See the treatments",
    cta_appeler: "Call",
    cta_whatsapp: "WhatsApp",
    demo: "Demo version: contact details, prices and images are provisional.",
    traduction: "Translation in progress: some text is shown in French.",
    image_synthese: "Synthetic image",
    ilustracja_alt: "Evolution Body Lab illustration",
    h_sur: "Nice · Côte d’Azur",
    h_titre: "Body contouring in Nice",
    h_lead: "Two treatments, a clear protocol from the first session and prices shown upfront. By appointment, Monday to Friday.",
    h_info: "Monika welcomes you in French and Polish.",
    h_wielki: "Evolution",
    h_pas_1: "EMS · Cryolipolysis · Nice · ",
    h_pas_2: "Silhouette · Firmness · Côte d’Azur · ",
    st_1: "Appointment",
    st_2: "Assessment",
    st_3: "Protocol",
    st_4: "Session",
    st_5: "Follow-up",
    st_6: "Evolution",
    man_label: "Our approach",
    manifeste: "A *clear* protocol. Prices shown *upfront*. *Precise* treatments, in Nice.",
    portal_entrer: "Scroll to enter",
    obj_label: "Your goals",
    obj_titre: "Where to start?",
    obj_1_t: "Muscle tone",
    obj_1_d: "Work your muscles in short, regular sessions.",
    obj_2_t: "Firmness",
    obj_2_d: "A steady rhythm of sessions to work on body tone.",
    obj_3_t: "Silhouette",
    obj_3_d: "Stomach, hips, thighs: targeted work, one area at a time.",
    obj_4_t: "Consistency",
    obj_4_d: "A planned rhythm of sessions, tracked with measurements.",
    soins_label: "Treatments",
    soins_titre: "Each treatment and its price",
    soins_fond: "Treatments",
    soins_defiler: "Scroll",
    soins_fin: "The right treatment, the number of sessions and the total price are set at the first visit.",
    soins_test: "Only two treatments: EMS and cryolipolysis.",
    tor_fond: "Evolution Body Lab",
    tor_3_lien: "How the visit works",
    tor_3_nad: "Before any treatment · consultation",
    s_ems_t: "EMS",
    s_ems_d: "Supervised electrical muscle stimulation: regular training, planned with you.",
    s_cryo_t: "Cryolipolysis",
    s_cryo_d: "Controlled cold applied to a precise area. €180 for one area, €350 for two, €500 for three.",
    duree: "min",
    prix_tbc: "Price to be confirmed (TEST)",
    par_seance: "per session",
    a_partir: "from",
    reserver_soin: "Book this treatment",
    visite_label: "First visit",
    visite_mot_1: "First",
    visite_mot_2: "visit",
    visite_titre: "How the first visit works",
    v1_t: "Conversation",
    v1_d: "Your goals, your history, a questionnaire filled in on site.",
    v2_t: "Measurements",
    v2_d: "Measurements taken to track your results session after session.",
    v3_t: "Protocol",
    v3_d: "The right treatment, the number and rhythm of sessions, the total price.",
    v4_t: "First treatment",
    v4_d: "If you wish, the first treatment can take place the same day.",
    visite_pratique: "Allow about 1 hour. Comfortable clothing, no special preparation.",
    monika_label: "Your practitioner",
    monika_titre: "Monika",
    monika_alt: "Monika, Evolution Body Lab",
    monika_fond: "Monika",
    monika_citation: "Quote from Monika coming soon (TEST)",
    monika_txt: "Introduction, background and certifications coming soon (TEST).",
    monika_langues: "Languages: French, Polish.",
    faq_label: "Frequently asked questions",
    faq_titre: "Before you book",
    q1: "Does it hurt?",
    a1: "Most treatments are comfortable. You may feel warmth, cold or pressure depending on the technique; we talk about it before we start.",
    q2: "How many sessions do I need?",
    a2: "It depends on the treatment and your goal. The number of sessions and the total price are set at the first visit, before any commitment.",
    q3: "Are there contraindications?",
    a3: "Yes, depending on the treatment: pregnancy, some medications or health conditions. The first visit questionnaire is there to check them.",
    q4: "Can I cancel my appointment?",
    a4: "Yes. Cancellation terms to be confirmed (TEST).",
    q5: "Are results guaranteed?",
    a5: "No, and no one can honestly guarantee them. Results vary from person to person; we track them with regular measurements.",
    contact_label: "Contact",
    contact_titre: "Book your visit",
    horaires: "Opening hours",
    horaires_val: "Monday to Friday, 9 am to 7 pm · last appointment at 6 pm",
    weekend: "Closed on Saturday and Sunday",
    adresse: "Address",
    telephone: "Phone",
    langues: "Languages",
    langues_val: "Monika speaks French and Polish",
    rdv_off: "Online booking will open with the institute. Until then, call or write on WhatsApp.",
    tarifs_label: "Prices",
    tarifs_titre: "Treatment menu",
    tarifs_ems_sous: "Electrical muscle stimulation",
    tarifs_cryo_sous: "Controlled cold, area by area",
    tarif_seance: "Per session",
    tarif_zone: "area",
    tarif_zones: "areas",
    tarif_test: "To be confirmed (TEST)",
    tarifs_note: "Prices include VAT. The protocol and number of sessions are decided together at the first visit.",
    rdv_lead: "Choose a treatment, a day and a time. Your request is sent by WhatsApp or e-mail, then the institute replies to set the appointment.",
    rdv_etapes: "Request steps",
    rdv_e1: "Treatment",
    rdv_e2: "Date and time",
    rdv_e3: "Contact details",
    rdv_etape_sur: "Step {n} of 3",
    rdv_k1_t: "Which treatment are you interested in?",
    rdv_conseil_t: "First visit: consultation",
    rdv_conseil_d: "Conversation, measurements and a tailored protocol",
    rdv_k2_t: "Which day would suit you?",
    rdv_mois_prec: "Previous month",
    rdv_mois_suiv: "Next month",
    rdv_aujourdhui: "today",
    rdv_ferme: "closed",
    rdv_indispo: "unavailable",
    rdv_choisi: "selected",
    rdv_heure: "Preferred time",
    rdv_heure_vide: "First choose a day in the calendar.",
    rdv_k3_t: "Your contact details",
    rdv_nom: "First and last name",
    rdv_tel: "Phone",
    rdv_mail: "E-mail",
    rdv_facultatif: "(optional)",
    rdv_message: "Message",
    rdv_tel_aide: "Example: 06 12 34 56 78 or +33 6 12 34 56 78",
    rdv_message_aide: "A question, a preferred time… Please do not include health information: we discuss it in person at the first visit.",
    rdv_accord: "I agree that Evolution Body Lab may contact me about this request.",
    rdv_vie_privee: "Nothing is stored on this website: the request is sent from your WhatsApp or your e-mail.",
    rdv_continuer: "Continue",
    rdv_retour: "Back",
    rdv_preparer: "Prepare my request",
    rdv_err_soin: "Choose a treatment to continue.",
    rdv_err_date: "Choose a day, then a time.",
    rdv_err_nom: "Enter your first and last name.",
    rdv_err_tel: "Number not recognised. Example: 06 12 34 56 78 or +33 6 12 34 56 78.",
    rdv_err_mail: "Invalid e-mail address.",
    rdv_err_accord: "Tick the box so the institute can contact you.",
    rdv_recap_soin: "Treatment",
    rdv_recap_date: "Date",
    rdv_recap_heure: "Time",
    rdv_vide: "—",
    rdv_pret_t: "Request ready to send",
    rdv_pret_d: "This is not an appointment yet: the institute will reply to set the time.",
    rdv_envoyer_wa: "Send on WhatsApp",
    rdv_envoyer_mail: "Send by e-mail",
    rdv_modifier: "Edit my request",
    rdv_appel_t: "Prefer to talk?",
    rdv_msg_bonjour: "Bonjour, je souhaite demander un rendez-vous chez Evolution Body Lab.",
    rdv_msg_soin: "Soin",
    rdv_msg_date: "Date souhaitée",
    rdv_msg_heure: "Heure souhaitée",
    rdv_msg_nom: "Nom",
    rdv_msg_tel: "Téléphone",
    rdv_msg_mail: "E-mail",
    rdv_msg_message: "Message",
    rdv_msg_fin: "Merci de me recontacter pour fixer le rendez-vous.",
    rdv_mail_sujet: "Demande de rendez-vous",
    footer_legal: "Legal notice",
    footer_siret: "SIRET",
    footer_slogan: "Every treatment has its *method*.",
    footer_pages: "Pages",
    footer_contact: "Contact",
    kursor_voir: "View",
    kursor_reserver: "Book",
    kursor_glisser: "Drag",
    menu_ouvrir: "Open menu",
    menu_fermer: "Close menu",
    menu_nav: "Navigation",
    menu_langues: "Languages"
  },
  es: {
    meta_title: "Evolution Body Lab · Remodelación corporal en Niza",
    meta_desc: "EMS y criolipólisis en Niza. Precios publicados, primera visita con cita previa, de lunes a viernes.",
    nav_accueil: "Inicio",
    nav_soins: "Tratamientos",
    nav_tarifs: "Precios",
    nav_visite: "Primera visita",
    nav_monika: "Monika",
    nav_faq: "Preguntas",
    nav_contact: "Contacto",
    cta_rdv: "Pedir cita",
    cta_rdv_court: "Cita",
    cta_soins: "Ver los tratamientos",
    cta_appeler: "Llamar",
    cta_whatsapp: "WhatsApp",
    demo: "Versión de demostración: datos de contacto, precios e imágenes son provisionales.",
    traduction: "Traducción en preparación: parte del texto se muestra en francés.",
    image_synthese: "Imagen sintética",
    ilustracja_alt: "Ilustración Evolution Body Lab",
    h_sur: "Niza · Costa Azul",
    h_titre: "Remodelación corporal en Niza",
    h_lead: "Dos tratamientos, un protocolo claro desde la primera sesión y precios publicados. Con cita previa, de lunes a viernes.",
    h_info: "Monika le atiende en francés y en polaco.",
    h_wielki: "Evolution",
    h_pas_1: "EMS · Criolipólisis · Niza · ",
    h_pas_2: "Silueta · Firmeza · Costa Azul · ",
    st_1: "Cita",
    st_2: "Evaluación",
    st_3: "Protocolo",
    st_4: "Sesión",
    st_5: "Seguimiento",
    st_6: "Evolución",
    man_label: "Nuestro enfoque",
    manifeste: "Un protocolo *claro*. Precios *publicados*. Tratamientos *precisos*, en Niza.",
    portal_entrer: "Desplácese para entrar",
    obj_label: "Sus objetivos",
    obj_titre: "¿Por dónde empezar?",
    obj_1_t: "Tono muscular",
    obj_1_d: "Trabajar los músculos en sesiones cortas y regulares.",
    obj_2_t: "Firmeza",
    obj_2_d: "Un ritmo de sesiones para trabajar el tono del cuerpo.",
    obj_3_t: "Silueta",
    obj_3_d: "Abdomen, caderas, muslos: un trabajo localizado, zona por zona.",
    obj_4_t: "Constancia",
    obj_4_d: "Un ritmo de sesiones planificado y seguido con mediciones.",
    soins_label: "Los tratamientos",
    soins_titre: "Cada tratamiento y su precio",
    soins_fond: "Tratamientos",
    soins_defiler: "Desplácese",
    soins_fin: "El tratamiento adecuado, el número de sesiones y el precio total se fijan en la primera visita.",
    soins_test: "Solo dos tratamientos: EMS y criolipólisis.",
    tor_fond: "Evolution Body Lab",
    tor_3_lien: "Cómo es la visita",
    tor_3_nad: "Antes de cualquier tratamiento · consulta",
    s_ems_t: "EMS",
    s_ems_d: "Electroestimulación muscular en sesión supervisada: un entrenamiento regular, planificado con usted.",
    s_cryo_t: "Criolipólisis",
    s_cryo_d: "Frío controlado aplicado en una zona precisa. 180 € una zona, 350 € dos zonas, 500 € tres zonas.",
    duree: "min",
    prix_tbc: "Precio por confirmar (TEST)",
    par_seance: "la sesión",
    a_partir: "desde",
    reserver_soin: "Reservar este tratamiento",
    visite_label: "Primera visita",
    visite_mot_1: "Primera",
    visite_mot_2: "visita",
    visite_titre: "Cómo es la primera visita",
    v1_t: "Conversación",
    v1_d: "Sus objetivos, sus antecedentes, un cuestionario que se rellena en el centro.",
    v2_t: "Mediciones",
    v2_d: "Toma de medidas para seguir sus resultados sesión tras sesión.",
    v3_t: "Protocolo",
    v3_d: "El tratamiento adecuado, el número y el ritmo de las sesiones, el precio total.",
    v4_t: "Primer tratamiento",
    v4_d: "Si lo desea, el primer tratamiento puede hacerse el mismo día.",
    visite_pratique: "Cuente con aproximadamente 1 h. Ropa cómoda, sin preparación especial.",
    monika_label: "Su especialista",
    monika_titre: "Monika",
    monika_alt: "Monika, Evolution Body Lab",
    monika_fond: "Monika",
    monika_citation: "Cita de Monika próximamente (TEST)",
    monika_txt: "Presentación, trayectoria y certificaciones próximamente (TEST).",
    monika_langues: "Idiomas: francés, polaco.",
    faq_label: "Preguntas frecuentes",
    faq_titre: "Antes de reservar",
    q1: "¿Duele?",
    a1: "La mayoría de los tratamientos son cómodos. Según la técnica, puede notar calor, frío o presión; lo hablamos antes de empezar.",
    q2: "¿Cuántas sesiones necesito?",
    a2: "Depende del tratamiento y de su objetivo. El número de sesiones y el precio total se fijan en la primera visita, antes de cualquier compromiso.",
    q3: "¿Hay contraindicaciones?",
    a3: "Sí, según el tratamiento: embarazo, algunos medicamentos o problemas de salud. El cuestionario de la primera visita sirve para comprobarlo.",
    q4: "¿Puedo cancelar mi cita?",
    a4: "Sí. Condiciones de cancelación por confirmar (TEST).",
    q5: "¿Los resultados están garantizados?",
    a5: "No, y nadie puede garantizarlos honestamente. Los resultados varían según cada persona; los seguimos con mediciones regulares.",
    contact_label: "Contacto",
    contact_titre: "Reserve su visita",
    horaires: "Horario",
    horaires_val: "De lunes a viernes, de 9 h a 19 h · última cita a las 18 h",
    weekend: "Cerrado sábados y domingos",
    adresse: "Dirección",
    telephone: "Teléfono",
    langues: "Idiomas",
    langues_val: "Monika habla francés y polaco",
    rdv_off: "La reserva en línea se abrirá con el centro. Mientras tanto, llame o escriba por WhatsApp.",
    tarifs_label: "Precios",
    tarifs_titre: "La carta de tratamientos",
    tarifs_ems_sous: "Electroestimulación muscular",
    tarifs_cryo_sous: "Frío controlado, zona por zona",
    tarif_seance: "La sesión",
    tarif_zone: "zona",
    tarif_zones: "zonas",
    tarif_test: "Por confirmar (TEST)",
    tarifs_note: "Precios con IVA incluido. El protocolo y el número de sesiones se deciden juntos en la primera visita.",
    rdv_lead: "Elija un tratamiento, un día y una hora. Su solicitud se envía por WhatsApp o por correo electrónico y el centro le responde para fijar la cita.",
    rdv_etapes: "Pasos de la solicitud",
    rdv_e1: "Tratamiento",
    rdv_e2: "Fecha y hora",
    rdv_e3: "Datos de contacto",
    rdv_etape_sur: "Paso {n} de 3",
    rdv_k1_t: "¿Qué tratamiento le interesa?",
    rdv_conseil_t: "Primera visita: consulta",
    rdv_conseil_d: "Conversación, mediciones y protocolo adaptado",
    rdv_k2_t: "¿Qué día le vendría bien?",
    rdv_mois_prec: "Mes anterior",
    rdv_mois_suiv: "Mes siguiente",
    rdv_aujourdhui: "hoy",
    rdv_ferme: "cerrado",
    rdv_indispo: "no disponible",
    rdv_choisi: "seleccionado",
    rdv_heure: "Hora deseada",
    rdv_heure_vide: "Primero elija un día en el calendario.",
    rdv_k3_t: "Sus datos de contacto",
    rdv_nom: "Nombre y apellidos",
    rdv_tel: "Teléfono",
    rdv_mail: "Correo electrónico",
    rdv_facultatif: "(opcional)",
    rdv_message: "Mensaje",
    rdv_tel_aide: "Ejemplo: 06 12 34 56 78 o +33 6 12 34 56 78",
    rdv_message_aide: "Una pregunta, una preferencia de horario… Por favor, no indique información de salud: la hablamos en persona en la primera visita.",
    rdv_accord: "Acepto que Evolution Body Lab se ponga en contacto conmigo sobre esta solicitud.",
    rdv_vie_privee: "Este sitio no guarda nada: la solicitud sale desde su WhatsApp o su correo.",
    rdv_continuer: "Continuar",
    rdv_retour: "Volver",
    rdv_preparer: "Preparar mi solicitud",
    rdv_err_soin: "Elija un tratamiento para continuar.",
    rdv_err_date: "Elija un día y después una hora.",
    rdv_err_nom: "Indique su nombre y apellidos.",
    rdv_err_tel: "Número no reconocido. Ejemplo: 06 12 34 56 78 o +33 6 12 34 56 78.",
    rdv_err_mail: "Dirección de correo no válida.",
    rdv_err_accord: "Marque la casilla para que el centro pueda contactarle.",
    rdv_recap_soin: "Tratamiento",
    rdv_recap_date: "Fecha",
    rdv_recap_heure: "Hora",
    rdv_vide: "—",
    rdv_pret_t: "Solicitud lista para enviar",
    rdv_pret_d: "Todavía no es una cita: el centro le responderá para fijar el horario.",
    rdv_envoyer_wa: "Enviar por WhatsApp",
    rdv_envoyer_mail: "Enviar por correo",
    rdv_modifier: "Modificar mi solicitud",
    rdv_appel_t: "¿Prefiere hablarlo?",
    rdv_msg_bonjour: "Bonjour, je souhaite demander un rendez-vous chez Evolution Body Lab.",
    rdv_msg_soin: "Soin",
    rdv_msg_date: "Date souhaitée",
    rdv_msg_heure: "Heure souhaitée",
    rdv_msg_nom: "Nom",
    rdv_msg_tel: "Téléphone",
    rdv_msg_mail: "E-mail",
    rdv_msg_message: "Message",
    rdv_msg_fin: "Merci de me recontacter pour fixer le rendez-vous.",
    rdv_mail_sujet: "Demande de rendez-vous",
    footer_legal: "Aviso legal",
    footer_siret: "SIRET",
    footer_slogan: "Cada tratamiento tiene su *método*.",
    footer_pages: "Páginas",
    footer_contact: "Contacto",
    kursor_voir: "Ver",
    kursor_reserver: "Reservar",
    kursor_glisser: "Deslizar",
    menu_ouvrir: "Abrir el menú",
    menu_fermer: "Cerrar el menú",
    menu_nav: "Navegación",
    menu_langues: "Idiomas"
  },
  pl: {
    meta_title: "Evolution Body Lab · Modelowanie sylwetki w Nicei",
    meta_desc: "EMS i kriolipoliza w Nicei. Jawne ceny, pierwsza wizyta po umówieniu, od poniedziałku do piątku.",
    nav_accueil: "Start",
    nav_soins: "Zabiegi",
    nav_tarifs: "Cennik",
    nav_visite: "Pierwsza wizyta",
    nav_monika: "Monika",
    nav_faq: "Pytania",
    nav_contact: "Kontakt",
    cta_rdv: "Umów wizytę",
    cta_rdv_court: "Wizyta",
    cta_soins: "Zobacz zabiegi",
    cta_appeler: "Zadzwoń",
    cta_whatsapp: "WhatsApp",
    demo: "Wersja demonstracyjna: dane kontaktowe, ceny i zdjęcia są tymczasowe.",
    traduction: "Tłumaczenie w przygotowaniu: część tekstu jest po francusku.",
    image_synthese: "Obraz wygenerowany",
    ilustracja_alt: "Ilustracja Evolution Body Lab",
    h_sur: "Nicea · Lazurowe Wybrzeże",
    h_titre: "Modelowanie sylwetki w Nicei",
    h_lead: "Dwa zabiegi, jasny plan od pierwszej sesji i jawne ceny. Po umówieniu, od poniedziałku do piątku.",
    h_info: "Monika przyjmuje po francusku i po polsku.",
    h_wielki: "Evolution",
    h_pas_1: "EMS · Kriolipoliza · Nicea · ",
    h_pas_2: "Sylwetka · Jędrność · Lazurowe Wybrzeże · ",
    st_1: "Wizyta",
    st_2: "Ocena",
    st_3: "Plan",
    st_4: "Zabieg",
    st_5: "Kontrola",
    st_6: "Postępy",
    man_label: "Nasze podejście",
    manifeste: "*Jasny* plan. *Jawne* ceny. *Precyzyjne* zabiegi, w Nicei.",
    portal_entrer: "Przewiń, aby wejść",
    obj_label: "Twoje cele",
    obj_titre: "Od czego zacząć?",
    obj_1_t: "Napięcie mięśni",
    obj_1_d: "Praca nad mięśniami w krótkich, regularnych sesjach.",
    obj_2_t: "Jędrność",
    obj_2_d: "Rytm sesji, który pracuje nad jędrnością ciała.",
    obj_3_t: "Sylwetka",
    obj_3_d: "Brzuch, biodra, uda: praca celowana, strefa po strefie.",
    obj_4_t: "Regularność",
    obj_4_d: "Zaplanowany rytm sesji, sprawdzany pomiarami.",
    soins_label: "Zabiegi",
    soins_titre: "Każdy zabieg i jego cena",
    soins_fond: "Zabiegi",
    soins_defiler: "Przewiń",
    soins_fin: "Odpowiedni zabieg, liczbę sesji i całkowitą cenę ustalamy na pierwszej wizycie.",
    soins_test: "Tylko dwa zabiegi: EMS i kriolipoliza.",
    tor_fond: "Evolution Body Lab",
    tor_3_lien: "Jak wygląda wizyta",
    tor_3_nad: "Przed każdym zabiegiem · konsultacja",
    s_ems_t: "EMS",
    s_ems_d: "Elektrostymulacja mięśni pod opieką: regularny trening, zaplanowany razem z Tobą.",
    s_cryo_t: "Kriolipoliza",
    s_cryo_d: "Kontrolowane zimno na wybraną strefę. 180 € jedna strefa, 350 € dwie strefy, 500 € trzy strefy.",
    duree: "min",
    prix_tbc: "Cena do potwierdzenia (TEST)",
    par_seance: "za sesję",
    a_partir: "od",
    reserver_soin: "Zarezerwuj ten zabieg",
    visite_label: "Pierwsza wizyta",
    visite_mot_1: "Pierwsza",
    visite_mot_2: "wizyta",
    visite_titre: "Jak wygląda pierwsza wizyta",
    v1_t: "Rozmowa",
    v1_d: "Twoje cele, Twoja historia zdrowia, ankieta wypełniana na miejscu.",
    v2_t: "Pomiary",
    v2_d: "Pomiary, dzięki którym śledzimy wyniki sesja po sesji.",
    v3_t: "Plan",
    v3_d: "Odpowiedni zabieg, liczba i rytm sesji, całkowita cena.",
    v4_t: "Pierwszy zabieg",
    v4_d: "Jeśli chcesz, pierwszy zabieg odbędzie się tego samego dnia.",
    visite_pratique: "Zarezerwuj około godziny. Wygodny strój, bez specjalnych przygotowań.",
    monika_label: "Twoja specjalistka",
    monika_titre: "Monika",
    monika_alt: "Monika, Evolution Body Lab",
    monika_fond: "Monika",
    monika_citation: "Cytat Moniki wkrótce (TEST)",
    monika_txt: "Prezentacja, doświadczenie i certyfikaty wkrótce (TEST).",
    monika_langues: "Języki: francuski, polski.",
    faq_label: "Częste pytania",
    faq_titre: "Zanim zarezerwujesz",
    q1: "Czy to boli?",
    a1: "Większość zabiegów jest komfortowa. Zależnie od techniki możesz poczuć ciepło, zimno albo ucisk; rozmawiamy o tym przed rozpoczęciem.",
    q2: "Ile sesji potrzeba?",
    a2: "To zależy od zabiegu i Twojego celu. Liczbę sesji i całkowitą cenę ustalamy na pierwszej wizycie, zanim cokolwiek zdecydujesz.",
    q3: "Czy są przeciwwskazania?",
    a3: "Tak, zależnie od zabiegu: ciąża, niektóre leki lub problemy zdrowotne. Ankieta na pierwszej wizycie służy do ich sprawdzenia.",
    q4: "Czy mogę odwołać wizytę?",
    a4: "Tak. Warunki odwołania do potwierdzenia (TEST).",
    q5: "Czy efekty są gwarantowane?",
    a5: "Nie, i nikt nie może ich uczciwie zagwarantować. Efekty są różne u każdej osoby; śledzimy je regularnymi pomiarami.",
    contact_label: "Kontakt",
    contact_titre: "Zarezerwuj wizytę",
    horaires: "Godziny otwarcia",
    horaires_val: "Od poniedziałku do piątku, 9:00 do 19:00 · ostatnia wizyta o 18:00",
    weekend: "Zamknięte w sobotę i niedzielę",
    adresse: "Adres",
    telephone: "Telefon",
    langues: "Języki",
    langues_val: "Monika mówi po francusku i po polsku",
    rdv_off: "Rezerwacja online ruszy razem z gabinetem. Do tego czasu zadzwoń lub napisz na WhatsAppie.",
    tarifs_label: "Cennik",
    tarifs_titre: "Karta zabiegów",
    tarifs_ems_sous: "Elektrostymulacja mięśni",
    tarifs_cryo_sous: "Kontrolowane zimno, strefa po strefie",
    tarif_seance: "Sesja",
    tarif_zone: "strefa",
    tarif_zones: "strefy",
    tarif_test: "Do potwierdzenia (TEST)",
    tarifs_note: "Ceny brutto. Plan i liczbę sesji ustalamy razem na pierwszej wizycie.",
    rdv_lead: "Wybierz zabieg, dzień i godzinę. Prośba wyjdzie przez WhatsApp lub e-mail, a gabinet odpowie, żeby ustalić termin.",
    rdv_etapes: "Kroki prośby",
    rdv_e1: "Zabieg",
    rdv_e2: "Data i godzina",
    rdv_e3: "Dane kontaktowe",
    rdv_etape_sur: "Krok {n} z 3",
    rdv_k1_t: "Jaki zabieg Cię interesuje?",
    rdv_conseil_t: "Pierwsza wizyta: konsultacja",
    rdv_conseil_d: "Rozmowa, pomiary i dopasowany plan",
    rdv_k2_t: "Który dzień Ci pasuje?",
    rdv_mois_prec: "Poprzedni miesiąc",
    rdv_mois_suiv: "Następny miesiąc",
    rdv_aujourdhui: "dziś",
    rdv_ferme: "zamknięte",
    rdv_indispo: "niedostępne",
    rdv_choisi: "wybrane",
    rdv_heure: "Preferowana godzina",
    rdv_heure_vide: "Najpierw wybierz dzień w kalendarzu.",
    rdv_k3_t: "Twoje dane",
    rdv_nom: "Imię i nazwisko",
    rdv_tel: "Telefon",
    rdv_mail: "E-mail",
    rdv_facultatif: "(opcjonalnie)",
    rdv_message: "Wiadomość",
    rdv_tel_aide: "Przykład: 06 12 34 56 78 lub +33 6 12 34 56 78",
    rdv_message_aide: "Pytanie, preferowana pora… Prosimy nie wpisywać informacji o zdrowiu: porozmawiamy o tym na miejscu, na pierwszej wizycie.",
    rdv_accord: "Zgadzam się, aby Evolution Body Lab skontaktowało się ze mną w sprawie tej prośby.",
    rdv_vie_privee: "Strona niczego nie zapisuje: prośba wychodzi z Twojego WhatsAppa lub poczty.",
    rdv_continuer: "Dalej",
    rdv_retour: "Wstecz",
    rdv_preparer: "Przygotuj prośbę",
    rdv_err_soin: "Wybierz zabieg, aby przejść dalej.",
    rdv_err_date: "Wybierz dzień, a potem godzinę.",
    rdv_err_nom: "Podaj imię i nazwisko.",
    rdv_err_tel: "Nie rozpoznano numeru. Przykład: 06 12 34 56 78 lub +33 6 12 34 56 78.",
    rdv_err_mail: "Nieprawidłowy adres e-mail.",
    rdv_err_accord: "Zaznacz pole, aby gabinet mógł się z Tobą skontaktować.",
    rdv_recap_soin: "Zabieg",
    rdv_recap_date: "Data",
    rdv_recap_heure: "Godzina",
    rdv_vide: "—",
    rdv_pret_t: "Prośba gotowa do wysłania",
    rdv_pret_d: "To jeszcze nie jest wizyta: gabinet odpowie, żeby ustalić termin.",
    rdv_envoyer_wa: "Wyślij na WhatsAppie",
    rdv_envoyer_mail: "Wyślij e-mailem",
    rdv_modifier: "Zmień prośbę",
    rdv_appel_t: "Wolisz porozmawiać?",
    rdv_msg_bonjour: "Dzień dobry, proszę o umówienie wizyty w Evolution Body Lab.",
    rdv_msg_soin: "Zabieg",
    rdv_msg_date: "Preferowana data",
    rdv_msg_heure: "Preferowana godzina",
    rdv_msg_nom: "Imię i nazwisko",
    rdv_msg_tel: "Telefon",
    rdv_msg_mail: "E-mail",
    rdv_msg_message: "Wiadomość",
    rdv_msg_fin: "Proszę o kontakt w celu ustalenia terminu.",
    rdv_mail_sujet: "Prośba o wizytę",
    footer_legal: "Informacje prawne",
    footer_siret: "SIRET",
    footer_slogan: "Każdy zabieg ma swoją *metodę*.",
    footer_pages: "Strony",
    footer_contact: "Kontakt",
    kursor_voir: "Zobacz",
    kursor_reserver: "Rezerwuj",
    kursor_glisser: "Przesuń",
    menu_ouvrir: "Otwórz menu",
    menu_fermer: "Zamknij menu",
    menu_nav: "Nawigacja",
    menu_langues: "Języki"
  },
  ru: {
    meta_title: "Evolution Body Lab · Коррекция фигуры в Ницце",
    meta_desc: "EMS и криолиполиз в Ницце. Цены указаны заранее, первый визит по записи, с понедельника по пятницу.",
    nav_accueil: "Главная",
    nav_soins: "Процедуры",
    nav_tarifs: "Цены",
    nav_visite: "Первый визит",
    nav_monika: "Моника",
    nav_faq: "Вопросы",
    nav_contact: "Контакты",
    cta_rdv: "Записаться",
    cta_rdv_court: "Запись",
    cta_soins: "Смотреть процедуры",
    cta_appeler: "Позвонить",
    cta_whatsapp: "WhatsApp",
    demo: "Демоверсия: контакты, цены и изображения предварительные.",
    traduction: "Перевод готовится: часть текста показана на французском.",
    image_synthese: "ИИ-изображение",
    ilustracja_alt: "Иллюстрация Evolution Body Lab",
    h_sur: "Ницца · Лазурный берег",
    h_titre: "Коррекция фигуры в Ницце",
    h_lead: "Две процедуры, понятный план с первого сеанса и цены, указанные заранее. По записи, с понедельника по пятницу.",
    h_info: "Моника принимает на французском и польском языках.",
    h_wielki: "Evolution",
    h_pas_1: "EMS · Криолиполиз · Ницца · ",
    h_pas_2: "Силуэт · Упругость · Лазурный берег · ",
    st_1: "Запись",
    st_2: "Оценка",
    st_3: "План",
    st_4: "Сеанс",
    st_5: "Контроль",
    st_6: "Прогресс",
    man_label: "Наш подход",
    manifeste: "*Понятный* план. Цены *заранее*. *Точные* процедуры, в Ницце.",
    portal_entrer: "Прокрутите, чтобы войти",
    obj_label: "Ваши цели",
    obj_titre: "С чего начать?",
    obj_1_t: "Тонус",
    obj_1_d: "Работа с мышцами в коротких регулярных сеансах.",
    obj_2_t: "Упругость",
    obj_2_d: "Ритм сеансов для работы над тонусом тела.",
    obj_3_t: "Силуэт",
    obj_3_d: "Живот, бёдра, ноги: точечная работа, зона за зоной.",
    obj_4_t: "Регулярность",
    obj_4_d: "Запланированный ритм сеансов с контрольными замерами.",
    soins_label: "Процедуры",
    soins_titre: "Каждая процедура и её цена",
    soins_fond: "Процедуры",
    soins_defiler: "Прокрутите",
    soins_fin: "Подходящую процедуру, число сеансов и общую цену определяем на первом визите.",
    soins_test: "Только две процедуры: EMS и криолиполиз.",
    tor_fond: "Evolution Body Lab",
    tor_3_lien: "Как проходит визит",
    tor_3_nad: "Перед любой процедурой · консультация",
    s_ems_t: "EMS",
    s_ems_d: "Электромиостимуляция под контролем специалиста: регулярная тренировка, спланированная вместе с вами.",
    s_cryo_t: "Криолиполиз",
    s_cryo_d: "Контролируемый холод на выбранной зоне. 180 € одна зона, 350 € две зоны, 500 € три зоны.",
    duree: "мин",
    prix_tbc: "Цена уточняется (TEST)",
    par_seance: "за сеанс",
    a_partir: "от",
    reserver_soin: "Записаться на процедуру",
    visite_label: "Первый визит",
    visite_mot_1: "Первый",
    visite_mot_2: "визит",
    visite_titre: "Как проходит первый визит",
    v1_t: "Беседа",
    v1_d: "Ваши цели, ваш анамнез, анкета, которую заполняют на месте.",
    v2_t: "Замеры",
    v2_d: "Замеры, чтобы следить за результатами от сеанса к сеансу.",
    v3_t: "План",
    v3_d: "Подходящая процедура, число и ритм сеансов, общая цена.",
    v4_t: "Первая процедура",
    v4_d: "По вашему желанию первая процедура может пройти в тот же день.",
    visite_pratique: "Заложите около часа. Удобная одежда, особая подготовка не нужна.",
    monika_label: "Ваш специалист",
    monika_titre: "Моника",
    monika_alt: "Моника, Evolution Body Lab",
    monika_fond: "Monika",
    monika_citation: "Цитата Моники скоро появится (TEST)",
    monika_txt: "Представление, опыт и сертификаты скоро появятся (TEST).",
    monika_langues: "Языки: французский, польский.",
    faq_label: "Частые вопросы",
    faq_titre: "Перед записью",
    q1: "Это больно?",
    a1: "Большинство процедур комфортны. В зависимости от техники возможно ощущение тепла, холода или давления; мы обсуждаем это перед началом.",
    q2: "Сколько нужно сеансов?",
    a2: "Это зависит от процедуры и вашей цели. Число сеансов и общую цену определяем на первом визите, до любых обязательств.",
    q3: "Есть ли противопоказания?",
    a3: "Да, в зависимости от процедуры: беременность, некоторые лекарства или проблемы со здоровьем. Анкета на первом визите нужна, чтобы это проверить.",
    q4: "Можно ли отменить запись?",
    a4: "Да. Условия отмены уточняются (TEST).",
    q5: "Гарантирован ли результат?",
    a5: "Нет, и никто не может честно его гарантировать. Результаты у всех разные; мы отслеживаем их регулярными замерами.",
    contact_label: "Контакты",
    contact_titre: "Запишитесь на визит",
    horaires: "Часы работы",
    horaires_val: "С понедельника по пятницу, с 9:00 до 19:00 · последняя запись в 18:00",
    weekend: "Суббота и воскресенье: выходной",
    adresse: "Адрес",
    telephone: "Телефон",
    langues: "Языки",
    langues_val: "Моника говорит по-французски и по-польски",
    rdv_off: "Онлайн-запись откроется вместе с салоном. А пока позвоните или напишите в WhatsApp.",
    tarifs_label: "Цены",
    tarifs_titre: "Прейскурант процедур",
    tarifs_ems_sous: "Электромиостимуляция",
    tarifs_cryo_sous: "Контролируемый холод, зона за зоной",
    tarif_seance: "Сеанс",
    tarif_zone: "зона",
    tarif_zones: "зоны",
    tarif_test: "Уточняется (TEST)",
    tarifs_note: "Цены с НДС. План и число сеансов определяем вместе на первом визите.",
    rdv_lead: "Выберите процедуру, день и время. Заявка уйдёт через WhatsApp или по e-mail, а салон ответит, чтобы назначить время.",
    rdv_etapes: "Шаги заявки",
    rdv_e1: "Процедура",
    rdv_e2: "Дата и время",
    rdv_e3: "Контакты",
    rdv_etape_sur: "Шаг {n} из 3",
    rdv_k1_t: "Какая процедура вас интересует?",
    rdv_conseil_t: "Первый визит: консультация",
    rdv_conseil_d: "Беседа, замеры и индивидуальный план",
    rdv_k2_t: "Какой день вам удобен?",
    rdv_mois_prec: "Предыдущий месяц",
    rdv_mois_suiv: "Следующий месяц",
    rdv_aujourdhui: "сегодня",
    rdv_ferme: "закрыто",
    rdv_indispo: "недоступно",
    rdv_choisi: "выбрано",
    rdv_heure: "Желаемое время",
    rdv_heure_vide: "Сначала выберите день в календаре.",
    rdv_k3_t: "Ваши контакты",
    rdv_nom: "Имя и фамилия",
    rdv_tel: "Телефон",
    rdv_mail: "E-mail",
    rdv_facultatif: "(необязательно)",
    rdv_message: "Сообщение",
    rdv_tel_aide: "Пример: 06 12 34 56 78 или +33 6 12 34 56 78",
    rdv_message_aide: "Вопрос, удобное время… Пожалуйста, не указывайте сведения о здоровье: обсудим это лично на первом визите.",
    rdv_accord: "Я согласна(ен), чтобы Evolution Body Lab связался со мной по этой заявке.",
    rdv_vie_privee: "Сайт ничего не сохраняет: заявка уходит из вашего WhatsApp или почты.",
    rdv_continuer: "Далее",
    rdv_retour: "Назад",
    rdv_preparer: "Подготовить заявку",
    rdv_err_soin: "Выберите процедуру, чтобы продолжить.",
    rdv_err_date: "Выберите день, затем время.",
    rdv_err_nom: "Укажите имя и фамилию.",
    rdv_err_tel: "Номер не распознан. Пример: 06 12 34 56 78 или +33 6 12 34 56 78.",
    rdv_err_mail: "Неверный адрес e-mail.",
    rdv_err_accord: "Отметьте поле, чтобы салон мог с вами связаться.",
    rdv_recap_soin: "Процедура",
    rdv_recap_date: "Дата",
    rdv_recap_heure: "Время",
    rdv_vide: "—",
    rdv_pret_t: "Заявка готова к отправке",
    rdv_pret_d: "Это ещё не запись: салон ответит, чтобы назначить время.",
    rdv_envoyer_wa: "Отправить в WhatsApp",
    rdv_envoyer_mail: "Отправить по e-mail",
    rdv_modifier: "Изменить заявку",
    rdv_appel_t: "Хотите обсудить по телефону?",
    rdv_msg_bonjour: "Bonjour, je souhaite demander un rendez-vous chez Evolution Body Lab.",
    rdv_msg_soin: "Soin",
    rdv_msg_date: "Date souhaitée",
    rdv_msg_heure: "Heure souhaitée",
    rdv_msg_nom: "Nom",
    rdv_msg_tel: "Téléphone",
    rdv_msg_mail: "E-mail",
    rdv_msg_message: "Message",
    rdv_msg_fin: "Merci de me recontacter pour fixer le rendez-vous.",
    rdv_mail_sujet: "Demande de rendez-vous",
    footer_legal: "Правовая информация",
    footer_siret: "SIRET",
    footer_slogan: "У каждой процедуры свой *метод*.",
    footer_pages: "Страницы",
    footer_contact: "Контакты",
    kursor_voir: "Смотреть",
    kursor_reserver: "Запись",
    kursor_glisser: "Листать",
    menu_ouvrir: "Открыть меню",
    menu_fermer: "Закрыть меню",
    menu_nav: "Навигация",
    menu_langues: "Языки"
  },
  de: {
    meta_title: "Evolution Body Lab · Körperformung in Nizza",
    meta_desc: "EMS und Kryolipolyse in Nizza. Transparente Preise, Erstbesuch nach Termin, Montag bis Freitag.",
    nav_accueil: "Start",
    nav_soins: "Behandlungen",
    nav_tarifs: "Preise",
    nav_visite: "Erstbesuch",
    nav_monika: "Monika",
    nav_faq: "Fragen",
    nav_contact: "Kontakt",
    cta_rdv: "Termin buchen",
    cta_rdv_court: "Termin",
    cta_soins: "Behandlungen ansehen",
    cta_appeler: "Anrufen",
    cta_whatsapp: "WhatsApp",
    demo: "Demoversion: Kontaktdaten, Preise und Bilder sind vorläufig.",
    traduction: "Übersetzung in Vorbereitung: ein Teil des Textes erscheint auf Französisch.",
    image_synthese: "KI-generiertes Bild",
    ilustracja_alt: "Illustration Evolution Body Lab",
    h_sur: "Nizza · Côte d’Azur",
    h_titre: "Körperformung in Nizza",
    h_lead: "Zwei Behandlungen, ein klarer Plan ab der ersten Sitzung und transparente Preise. Nach Termin, Montag bis Freitag.",
    h_info: "Monika empfängt Sie auf Französisch und Polnisch.",
    h_wielki: "Evolution",
    h_pas_1: "EMS · Kryolipolyse · Nizza · ",
    h_pas_2: "Silhouette · Straffheit · Côte d’Azur · ",
    st_1: "Termin",
    st_2: "Analyse",
    st_3: "Plan",
    st_4: "Sitzung",
    st_5: "Begleitung",
    st_6: "Entwicklung",
    man_label: "Unser Ansatz",
    manifeste: "Ein *klarer* Plan. *Transparente* Preise. *Präzise* Behandlungen, in Nizza.",
    portal_entrer: "Scrollen, um einzutreten",
    obj_label: "Ihre Ziele",
    obj_titre: "Womit beginnen?",
    obj_1_t: "Muskeltonus",
    obj_1_d: "Die Muskeln in kurzen, regelmäßigen Sitzungen trainieren.",
    obj_2_t: "Straffheit",
    obj_2_d: "Ein Sitzungsrhythmus, der am Tonus des Körpers arbeitet.",
    obj_3_t: "Silhouette",
    obj_3_d: "Bauch, Hüften, Oberschenkel: gezielte Arbeit, Zone für Zone.",
    obj_4_t: "Regelmäßigkeit",
    obj_4_d: "Ein geplanter Sitzungsrhythmus, begleitet von Messungen.",
    soins_label: "Behandlungen",
    soins_titre: "Jede Behandlung und ihr Preis",
    soins_fond: "Behandlungen",
    soins_defiler: "Scrollen",
    soins_fin: "Die passende Behandlung, die Zahl der Sitzungen und den Gesamtpreis legen wir beim Erstbesuch fest.",
    soins_test: "Nur zwei Behandlungen: EMS und Kryolipolyse.",
    tor_fond: "Evolution Body Lab",
    tor_3_lien: "So läuft der Besuch ab",
    tor_3_nad: "Vor jeder Behandlung · Beratung",
    s_ems_t: "EMS",
    s_ems_d: "Begleitete Elektromuskelstimulation: regelmäßiges Training, gemeinsam mit Ihnen geplant.",
    s_cryo_t: "Kryolipolyse",
    s_cryo_d: "Kontrollierte Kälte auf einer genau bestimmten Zone. 180 € eine Zone, 350 € zwei Zonen, 500 € drei Zonen.",
    duree: "Min.",
    prix_tbc: "Preis wird bestätigt (TEST)",
    par_seance: "pro Sitzung",
    a_partir: "ab",
    reserver_soin: "Diese Behandlung buchen",
    visite_label: "Erster Besuch",
    visite_mot_1: "Erster",
    visite_mot_2: "Besuch",
    visite_titre: "So läuft der Erstbesuch ab",
    v1_t: "Gespräch",
    v1_d: "Ihre Ziele, Ihre Vorgeschichte, ein Fragebogen vor Ort.",
    v2_t: "Messungen",
    v2_d: "Messungen, um Ihre Ergebnisse von Sitzung zu Sitzung zu verfolgen.",
    v3_t: "Plan",
    v3_d: "Die passende Behandlung, Zahl und Rhythmus der Sitzungen, der Gesamtpreis.",
    v4_t: "Erste Behandlung",
    v4_d: "Auf Wunsch findet die erste Behandlung noch am selben Tag statt.",
    visite_pratique: "Planen Sie etwa 1 Stunde ein. Bequeme Kleidung, keine besondere Vorbereitung.",
    monika_label: "Ihre Behandlerin",
    monika_titre: "Monika",
    monika_alt: "Monika, Evolution Body Lab",
    monika_fond: "Monika",
    monika_citation: "Zitat von Monika folgt (TEST)",
    monika_txt: "Vorstellung, Werdegang und Zertifikate folgen (TEST).",
    monika_langues: "Sprachen: Französisch, Polnisch.",
    faq_label: "Häufige Fragen",
    faq_titre: "Vor der Buchung",
    q1: "Tut es weh?",
    a1: "Die meisten Behandlungen sind angenehm. Je nach Technik spüren Sie Wärme, Kälte oder Druck; wir besprechen das vor dem Start.",
    q2: "Wie viele Sitzungen brauche ich?",
    a2: "Das hängt von der Behandlung und Ihrem Ziel ab. Die Zahl der Sitzungen und der Gesamtpreis werden beim Erstbesuch festgelegt, vor jeder Verpflichtung.",
    q3: "Gibt es Gegenanzeigen?",
    a3: "Ja, je nach Behandlung: Schwangerschaft, bestimmte Medikamente oder Erkrankungen. Der Fragebogen beim Erstbesuch dient dazu, sie zu prüfen.",
    q4: "Kann ich meinen Termin absagen?",
    a4: "Ja. Stornobedingungen werden bestätigt (TEST).",
    q5: "Sind die Ergebnisse garantiert?",
    a5: "Nein, und niemand kann sie ehrlich garantieren. Ergebnisse sind bei jedem Menschen anders; wir verfolgen sie mit regelmäßigen Messungen.",
    contact_label: "Kontakt",
    contact_titre: "Ihren Besuch buchen",
    horaires: "Öffnungszeiten",
    horaires_val: "Montag bis Freitag, 9 bis 19 Uhr · letzter Termin um 18 Uhr",
    weekend: "Samstag und Sonntag geschlossen",
    adresse: "Adresse",
    telephone: "Telefon",
    langues: "Sprachen",
    langues_val: "Monika spricht Französisch und Polnisch",
    rdv_off: "Die Online-Buchung startet mit der Eröffnung des Instituts. Bis dahin rufen Sie an oder schreiben per WhatsApp.",
    tarifs_label: "Preise",
    tarifs_titre: "Die Behandlungskarte",
    tarifs_ems_sous: "Elektromuskelstimulation",
    tarifs_cryo_sous: "Kontrollierte Kälte, Zone für Zone",
    tarif_seance: "Pro Sitzung",
    tarif_zone: "Zone",
    tarif_zones: "Zonen",
    tarif_test: "Wird bestätigt (TEST)",
    tarifs_note: "Preise inkl. MwSt. Plan und Zahl der Sitzungen legen wir gemeinsam beim Erstbesuch fest.",
    rdv_lead: "Wählen Sie eine Behandlung, einen Tag und eine Uhrzeit. Ihre Anfrage geht per WhatsApp oder E-Mail raus, dann meldet sich das Institut, um den Termin festzulegen.",
    rdv_etapes: "Schritte der Anfrage",
    rdv_e1: "Behandlung",
    rdv_e2: "Datum und Uhrzeit",
    rdv_e3: "Kontakt­daten",
    rdv_etape_sur: "Schritt {n} von 3",
    rdv_k1_t: "Welche Behandlung interessiert Sie?",
    rdv_conseil_t: "Erstbesuch: Beratung",
    rdv_conseil_d: "Gespräch, Messungen und ein passender Plan",
    rdv_k2_t: "Welcher Tag passt Ihnen?",
    rdv_mois_prec: "Vorheriger Monat",
    rdv_mois_suiv: "Nächster Monat",
    rdv_aujourdhui: "heute",
    rdv_ferme: "geschlossen",
    rdv_indispo: "nicht verfügbar",
    rdv_choisi: "ausgewählt",
    rdv_heure: "Gewünschte Uhrzeit",
    rdv_heure_vide: "Wählen Sie zuerst einen Tag im Kalender.",
    rdv_k3_t: "Ihre Kontaktdaten",
    rdv_nom: "Vor- und Nachname",
    rdv_tel: "Telefon",
    rdv_mail: "E-Mail",
    rdv_facultatif: "(optional)",
    rdv_message: "Nachricht",
    rdv_tel_aide: "Beispiel: 06 12 34 56 78 oder +33 6 12 34 56 78",
    rdv_message_aide: "Eine Frage, eine Wunschzeit… Bitte keine Gesundheitsangaben: darüber sprechen wir persönlich beim Erstbesuch.",
    rdv_accord: "Ich bin einverstanden, dass Evolution Body Lab mich zu dieser Anfrage kontaktiert.",
    rdv_vie_privee: "Auf dieser Website wird nichts gespeichert: Die Anfrage geht aus Ihrem WhatsApp oder E-Mail-Programm raus.",
    rdv_continuer: "Weiter",
    rdv_retour: "Zurück",
    rdv_preparer: "Anfrage vorbereiten",
    rdv_err_soin: "Wählen Sie eine Behandlung, um fortzufahren.",
    rdv_err_date: "Wählen Sie einen Tag und dann eine Uhrzeit.",
    rdv_err_nom: "Geben Sie Vor- und Nachnamen an.",
    rdv_err_tel: "Nummer nicht erkannt. Beispiel: 06 12 34 56 78 oder +33 6 12 34 56 78.",
    rdv_err_mail: "Ungültige E-Mail-Adresse.",
    rdv_err_accord: "Kreuzen Sie das Feld an, damit das Institut Sie kontaktieren kann.",
    rdv_recap_soin: "Behandlung",
    rdv_recap_date: "Datum",
    rdv_recap_heure: "Uhrzeit",
    rdv_vide: "—",
    rdv_pret_t: "Anfrage bereit zum Senden",
    rdv_pret_d: "Das ist noch kein Termin: Das Institut meldet sich, um die Uhrzeit festzulegen.",
    rdv_envoyer_wa: "Per WhatsApp senden",
    rdv_envoyer_mail: "Per E-Mail senden",
    rdv_modifier: "Anfrage ändern",
    rdv_appel_t: "Lieber persönlich sprechen?",
    rdv_msg_bonjour: "Bonjour, je souhaite demander un rendez-vous chez Evolution Body Lab.",
    rdv_msg_soin: "Soin",
    rdv_msg_date: "Date souhaitée",
    rdv_msg_heure: "Heure souhaitée",
    rdv_msg_nom: "Nom",
    rdv_msg_tel: "Téléphone",
    rdv_msg_mail: "E-mail",
    rdv_msg_message: "Message",
    rdv_msg_fin: "Merci de me recontacter pour fixer le rendez-vous.",
    rdv_mail_sujet: "Demande de rendez-vous",
    footer_legal: "Impressum",
    footer_siret: "SIRET",
    footer_slogan: "Jede Behandlung hat ihre *Methode*.",
    footer_pages: "Seiten",
    footer_contact: "Kontakt",
    kursor_voir: "Ansehen",
    kursor_reserver: "Buchen",
    kursor_glisser: "Ziehen",
    menu_ouvrir: "Menü öffnen",
    menu_fermer: "Menü schließen",
    menu_nav: "Navigation",
    menu_langues: "Sprachen"
  }
};
