// Teksty strony. Kolejność języków (Daniel 02.10.2026): FR, EN, ES, PL, RU, DE.
// Etap 1: francuski kompletny do akceptacji Moniki. Pozostałe języki tłumaczymy z francuskiego
// PO akceptacji (mniej poprawek x6). Brakujący klucz = tekst francuski + pasek „traduction en préparation”.
window.JEZYKI = ['fr', 'en', 'es', 'pl', 'ru', 'de'];
window.NAZWY_JEZYKOW = { fr: 'FR', en: 'EN', es: 'ES', pl: 'PL', ru: 'RU', de: 'DE' };

window.T = {
  fr: {
    meta_title: 'Evolution Body Lab · Remodelage de la silhouette à Nice',
    meta_desc: 'EMS et cryolipolyse à Nice. Tarifs affichés, première visite sur rendez-vous, du lundi au vendredi.',
    nav_soins: 'Soins', nav_tarifs: 'Tarifs', nav_visite: 'Première visite', nav_monika: 'Monika', nav_faq: 'Questions', nav_contact: 'Contact',
    cta_rdv: 'Prendre rendez-vous', cta_rdv_court: 'Rendez-vous', cta_soins: 'Voir les soins', cta_appeler: 'Appeler', cta_whatsapp: 'WhatsApp',
    demo: 'Version de démonstration : coordonnées, tarifs et images sont provisoires.',
    traduction: 'Traduction en préparation : le texte s’affiche en français.',
    image_synthese: 'Image de synthèse',
    ilustracja_alt: 'Illustration Evolution Body Lab',
    h_sur: 'Nice · Côte d’Azur',
    h_titre: 'Remodelage de la silhouette à Nice',
    h_lead: 'Deux soins, un protocole clair dès la première séance et des tarifs affichés. Sur rendez-vous, du lundi au vendredi.',
    h_info: 'Monika vous reçoit en français et en polonais.',
    h_wielki: 'Evolution',   // gigantyczny napis za Moniką w pierwszym ekranie (jak u Lando)
    h_pas_1: 'EMS · Cryolipolyse · Nice · ',
    h_pas_2: 'Silhouette · Fermeté · Côte d’Azur · ',
    st_1: 'Rendez-vous', st_2: 'Bilan', st_3: 'Protocole', st_4: 'Séance', st_5: 'Suivi', st_6: 'Évolution',
    man_label: 'Notre approche',
    manifeste: 'Un protocole *clair*. Des tarifs *affichés*. Des soins *précis*, à Nice.',
    // Teleport (#approche, js/petardy.js): wskazówka nad medalionem
    portal_entrer: 'Faites défiler pour entrer',
    obj_label: 'Vos objectifs',
    obj_titre: 'Par où commencer ?',
    obj_1_t: 'Tonicité', obj_1_d: 'Travailler les muscles en séances courtes et régulières.',
    obj_2_t: 'Fermeté', obj_2_d: 'Un rythme de séances pour travailler la tonicité du corps.',
    obj_3_t: 'Silhouette', obj_3_d: 'Ventre, hanches, cuisses : un travail ciblé, zone par zone.',
    obj_4_t: 'Régularité', obj_4_d: 'Un rythme de séances planifié, suivi par des mesures.',
    soins_label: 'Les soins',
    soins_titre: 'Chaque soin et son prix',
    soins_fond: 'Soins',
    soins_defiler: 'Faites défiler',
    soins_fin: 'Le soin adapté, le nombre de séances et le prix total sont fixés lors de la première visite.',
    soins_test: 'Deux soins seulement : l’EMS et la cryolipolyse.',
    // Tor 3 paneli (#soins, js/petardy.js): wielki napis w tle i link trzeciego panelu
    tor_fond: 'Evolution Body Lab',
    tor_3_lien: 'Le déroulé de la visite',
    tor_3_nad: 'Avant tout soin · consultation',   // podpis nad „Première visite” w torze: zamknięcie toru, nie trzeci zabieg
    s_ems_t: 'EMS', s_ems_d: 'Électrostimulation musculaire en séance encadrée : un entraînement régulier, planifié avec vous.',
    s_cryo_t: 'Cryolipolyse', s_cryo_d: 'Un froid contrôlé, appliqué sur une zone précise. 180 € une zone, 350 € deux zones, 500 € trois zones.',
    duree: 'min', prix_tbc: 'Tarif à confirmer (TEST)', par_seance: 'la séance', a_partir: 'à partir de', reserver_soin: 'Réserver ce soin',
    visite_label: 'Première visite',
    visite_mot_1: 'Première',
    visite_mot_2: 'visite',
    visite_titre: 'Comment se passe la première visite',
    v1_t: 'Échange', v1_d: 'Vos objectifs, vos antécédents, un questionnaire rempli sur place.',
    v2_t: 'Mesures', v2_d: 'Prise de mesures pour suivre vos résultats séance après séance.',
    v3_t: 'Protocole', v3_d: 'Le soin adapté, le nombre de séances et leur rythme, le prix total.',
    v4_t: 'Premier soin', v4_d: 'Si vous le souhaitez, le premier soin a lieu le jour même.',
    visite_pratique: 'Prévoir environ 1 h. Tenue confortable, aucune préparation particulière.',
    monika_label: 'Votre praticienne',
    monika_titre: 'Monika',
    monika_alt: "Monika, Evolution Body Lab",
    monika_fond: 'Monika',
    monika_citation: 'Citation de Monika à venir (TEST)',
    monika_txt: 'Présentation, parcours et certifications à venir (TEST).',
    monika_langues: 'Langues : français, polonais.',
    faq_label: 'Questions fréquentes',
    faq_titre: 'Avant de réserver',
    q1: 'Est-ce douloureux ?', a1: 'La plupart des soins sont confortables. Une sensation de chaleur, de froid ou de pression est possible selon la technique ; on en parle avant de commencer.',
    q2: 'Combien de séances faut-il ?', a2: 'Cela dépend du soin et de votre objectif. Le nombre de séances et le prix total sont fixés lors de la première visite, avant tout engagement.',
    q3: 'Y a-t-il des contre-indications ?', a3: 'Oui, selon les soins : grossesse, certains traitements ou problèmes de santé. Le questionnaire de la première visite sert à les vérifier.',
    q4: 'Puis-je annuler mon rendez-vous ?', a4: 'Oui. Conditions d’annulation à confirmer (TEST).',
    q5: 'Les résultats sont-ils garantis ?', a5: 'Non, et personne ne peut honnêtement les garantir. Les résultats varient selon chaque personne ; nous les suivons avec des mesures régulières.',
    contact_label: 'Contact',
    contact_titre: 'Prendre rendez-vous',
    horaires: 'Horaires', horaires_val: 'Du lundi au vendredi, 9 h à 19 h · dernier rendez-vous à 18 h',
    weekend: 'Fermé le samedi et le dimanche',
    adresse: 'Adresse', telephone: 'Téléphone', langues: 'Langues', langues_val: 'Monika parle français et polonais',
    rdv_off: 'La réservation en ligne ouvrira avec l’institut. En attendant, appelez ou écrivez sur WhatsApp.',
    // Cennik (#tarifs): ceny z js/dane.js (biznesplan Moniki), tu tylko słowa wokół liczb
    tarifs_label: 'Tarifs',
    tarifs_titre: 'La carte des soins',
    tarifs_ems_sous: 'Électrostimulation musculaire',
    tarifs_cryo_sous: 'Froid contrôlé, zone par zone',
    tarif_seance: 'La séance', tarif_zone: 'zone', tarif_zones: 'zones',
    tarif_test: 'À valider (TEST)',
    tarifs_note: 'Prix TTC. Le protocole et le nombre de séances sont fixés ensemble lors de la première visite.',
    // Demande de rendez-vous (#contact, js/rezerwacja.js). Jamais de réservation présentée comme acquise.
    rdv_lead: 'Choisissez un soin, un jour et une heure. Votre demande part sur WhatsApp ou par e-mail, puis l’institut vous répond pour fixer le rendez-vous.',
    rdv_etapes: 'Étapes de la demande',
    rdv_e1: 'Soin', rdv_e2: 'Date et heure', rdv_e3: 'Coordon\u00adnées',
    rdv_etape_sur: 'Étape {n} sur 3',
    rdv_k1_t: 'Quel soin vous intéresse ?',
    rdv_conseil_t: 'Première visite – conseil', rdv_conseil_d: 'Échange, mesures et protocole adapté',
    rdv_k2_t: 'Quel jour vous conviendrait ?',
    rdv_mois_prec: 'Mois précédent', rdv_mois_suiv: 'Mois suivant',
    rdv_aujourdhui: 'aujourd’hui', rdv_ferme: 'fermé', rdv_indispo: 'indisponible', rdv_choisi: 'sélectionné',
    rdv_heure: 'Heure souhaitée', rdv_heure_vide: 'Choisissez d’abord un jour dans le calendrier.',
    rdv_k3_t: 'Vos coordonnées',
    rdv_nom: 'Prénom et nom', rdv_tel: 'Téléphone', rdv_mail: 'E-mail', rdv_facultatif: '(facultatif)', rdv_message: 'Message',
    rdv_tel_aide: 'Exemple : 06 12 34 56 78 ou +33 6 12 34 56 78',
    rdv_message_aide: 'Une question, une préférence d’horaire… Merci de ne pas indiquer d’informations de santé : on en parle sur place, lors de la première visite.',
    rdv_accord: 'J’accepte qu’Evolution Body Lab me recontacte au sujet de cette demande.',
    rdv_vie_privee: 'Rien n’est enregistré sur ce site : la demande part depuis votre WhatsApp ou votre messagerie.',
    rdv_continuer: 'Continuer', rdv_retour: 'Retour', rdv_preparer: 'Préparer ma demande',
    rdv_err_soin: 'Choisissez un soin pour continuer.',
    rdv_err_date: 'Choisissez un jour, puis une heure.',
    rdv_err_nom: 'Indiquez votre prénom et votre nom.',
    rdv_err_tel: 'Numéro non reconnu. Exemple : 06 12 34 56 78 ou +33 6 12 34 56 78.',
    rdv_err_mail: 'Adresse e-mail non valide.',
    rdv_err_accord: 'Cochez la case pour que l’institut puisse vous recontacter.',
    rdv_recap_soin: 'Soin', rdv_recap_date: 'Date', rdv_recap_heure: 'Heure', rdv_vide: '—',
    rdv_pret_t: 'Demande prête à envoyer',
    rdv_pret_d: 'Ce n’est pas encore un rendez-vous : l’institut vous répond pour fixer le créneau.',
    rdv_envoyer_wa: 'Envoyer sur WhatsApp', rdv_envoyer_mail: 'Envoyer par e-mail', rdv_modifier: 'Modifier ma demande',
    rdv_appel_t: 'Vous préférez en parler ?',
    rdv_msg_bonjour: 'Bonjour, je souhaite demander un rendez-vous chez Evolution Body Lab.',
    rdv_msg_soin: 'Soin', rdv_msg_date: 'Date souhaitée', rdv_msg_heure: 'Heure souhaitée',
    rdv_msg_nom: 'Nom', rdv_msg_tel: 'Téléphone', rdv_msg_mail: 'E-mail', rdv_msg_message: 'Message',
    rdv_msg_fin: 'Merci de me recontacter pour fixer le rendez-vous.',
    rdv_mail_sujet: 'Demande de rendez-vous',
    footer_legal: 'Mentions légales', footer_siret: 'SIRET',
    footer_slogan: 'Chaque soin a sa *méthode*.',
    footer_pages: 'Pages', footer_contact: 'Contact',
    // Kursor-soczewka (js/efekty.js, tylko komputer z myszą): słowo w złotym kółku nad kartami, torem i zdjęciami
    kursor_voir: 'Voir', kursor_reserver: 'Réserver', kursor_glisser: 'Glisser',
    // Menu plein écran (js/silnik2.js, ordinateur) : bouton du bandeau, fermeture, nom de la navigation, langues
    menu_ouvrir: 'Ouvrir le menu', menu_fermer: 'Fermer le menu', menu_nav: 'Navigation', menu_langues: 'Langues'
  },
  en: {}, es: {}, pl: {}, ru: {}, de: {}
};
